defaults:
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

project:
  project_name: ChakraTrade
  project_dir: D:\ChakraTrade
  data_dir: D:\ChakraTrade\data
  test_data_dir: D:\ChakraTrade\tests\data
  plugins_dir: D:\ChakraTrade\src\plugIn